version: "3.8"

services:
  server:
    image: haseeb702/myapp-server:master
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SUPABASE_URL=SUPABASE_KEY
      - SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY
      - SENDGRID_API_KEY=SENDGRID_API_KEY
      - SENDGRID_SENDER=SENDGRID_SENDER
    restart: unless-stopped

  client:
    image: haseeb702/myapp-client:master
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://4.236.162.53:8080/api
      - NEXT_PUBLIC_SUPABASE_URL=SUPABASE_SERVICE_ROLE_KEY
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=SUPABASE_ANON_KEY
    restart: unless-stopped

  map:
    image: haseeb702/myapp-map:master
    environment:
      - SUPABASE_URL=SUPABASE_URL_KEY
      - SUPABASE_KEY=SUPABASE_KEY
    volumes:
      - ./map:/map
    working_dir: /map
    restart: unless-stopped